# Generated by Django 5.1.2 on 2024-10-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion',
            field=models.IntegerField(default='30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='es_disponibilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_inicio',
            field=models.TimeField(default='12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
