# Generated by Django 5.1.2 on 2024-10-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora_inicio',
            field=models.CharField(max_length=5),
        ),
    ]
