# Generated by Django 5.1.2 on 2024-10-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_rename_es_disponibilidad_cita_es_bloqueado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='estado',
        ),
        migrations.AddField(
            model_name='cita',
            name='estado_cita',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada_paciente', 'Cancelada por el Paciente'), ('cancelada_profesional', 'Cancelada por el Profesional')], default='pendiente', max_length=50),
        ),
    ]
