# Generated by Django 5.1.2 on 2024-11-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_ciudad_comuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='ciudad',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
    ]
